const dims=['Courage','Connection','Self-Respect','Creation','Growth'];
const identityCopy={Explorer:'You repeatedly move toward uncertainty instead of waiting to feel ready.',Connector:'You repeatedly reach toward people instead of staying separate.',Maker:'You repeatedly put things into the world instead of only thinking about them.',Grounded:'You repeatedly act in alignment with what matters to you.',Learner:'You repeatedly choose learning over protecting your ego.'};
let missions=[];let state=JSON.parse(localStorage.getItem('proof-v1')||'null')||{completed:[],dimensions:Object.fromEntries(dims.map(x=>[x,0])),identities:{Explorer:0,Connector:0,Maker:0,Grounded:0,Learner:0},current:null,resistance:{},feeling:null};
const $=s=>document.querySelector(s);const save=()=>localStorage.setItem('proof-v1',JSON.stringify(state));
function unlocked(m){return !state.completed.some(x=>x.id===m.id)&&m.prerequisites.every(p=>state.completed.some(x=>x.id===p&&!x.smaller));}
function chooseMission(){let pool=missions.filter(unlocked);if(!pool.length)return null;let last=state.completed.at(-1);if(last?.smaller){const retry=pool.find(x=>x.id===last.originalId);if(retry)return retry;}let lastDiff=last?last.difficulty:1;let weakest=[...dims].sort((a,b)=>state.dimensions[a]-state.dimensions[b]).slice(0,2);pool.sort((a,b)=>{const score=x=>{let s=0;if(last&&!last.smaller&&x.prerequisites.includes(last.id))s+=20;if(last)s+=x.dimensions.filter(d=>last.dimensions.includes(d)).length*2;s+=x.dimensions.filter(d=>weakest.includes(d)).length*4;s-=Math.max(0,x.difficulty-lastDiff-1)*8;s-=Math.abs(x.difficulty-lastDiff)*.8;s+=(last&&x.capability===last.capability)?2:0;s-=(state.resistance[x.id]||0)*2;return s};return score(b)-score(a)});return pool[0];}
function ensureCurrent(){if(!state.current){const m=chooseMission();state.current=m?.id||null;save()}return missions.find(m=>m.id===state.current)}
function diffDots(n){return `<span class="difficulty">${[1,2,3,4,5].map(x=>`<i class="dot ${x<=n?'on':''}"></i>`).join('')}</span>`}
function missionHTML(m){if(!m)return `<div class="empty">Season 1 complete. You have 50 Proofs.</div>`;return `<div class="meta"><span>${m.id.replace('P','PROOF #')}</span><span>~${m.minutes} MIN</span></div><h2>${m.title}</h2><p class="copy">${m.mission}</p><p class="hint">Difficulty ${m.difficulty}/5 ${diffDots(m.difficulty)}</p><div class="eyebrow">THIS BUILDS</div><div class="tags">${m.dimensions.map(x=>`<span class="pill">${x}</span>`).join('')}</div><button class="primary" id="accept">I'LL DO IT</button><button class="secondary" id="another">GIVE ME ANOTHER</button>`}
function renderPlay(){const m=ensureCurrent();$('#missionCard').innerHTML=missionHTML(m);$('#missionCard').classList.remove('hidden');$('#activeCard').classList.add('hidden');$('#notYetCard').classList.add('hidden');$('#provenCard').classList.add('hidden');if(!m)return;if(state.active){showActive(m,!!state.small);return;}$('#accept').onclick=()=>showActive(m);$('#another').onclick=()=>{state.current=null;let candidates=missions.filter(x=>unlocked(x)&&x.id!==m.id);state.current=(candidates[0]||chooseMission())?.id||null;save();renderPlay()}}
function showActive(m,small=false){state.active=true;state.small=small;save();$('#missionCard').classList.add('hidden');$('#activeCard').classList.remove('hidden');$('#activeCard').innerHTML=`<div class="eyebrow">MISSION ACTIVE</div><h2 class="active-title">${m.title}${small?" · SMALLER STEP":""}</h2><p class="copy">${small?m.notYet:m.mission}</p><p class="hint">Put the phone away. Come back when you've tried it.</p><button class="primary" id="done">✓ I DID IT</button><button class="secondary" id="notyet">NOT YET</button>`;$('#done').onclick=()=>showProven(m,small);$('#notyet').onclick=()=>showNotYet(m)}
function showNotYet(m){state.resistance[m.id]=(state.resistance[m.id]||0)+1;save();$('#activeCard').classList.add('hidden');$('#notYetCard').classList.remove('hidden');$('#notYetCard').innerHTML=`<div class="eyebrow">NOT YET ≠ FAILURE</div><h2 class="active-title">Same direction. Smaller step.</h2><p class="copy">${m.notYet}</p><p class="hint">PROOF reduces resistance. It doesn't punish it.</p><button class="primary" id="smallDone">I CAN DO THAT</button><button class="secondary" id="swap">TRY ANOTHER MISSION</button>`;$('#smallDone').onclick=()=>{$('#notYetCard').classList.add('hidden');showActive(m,true)};$('#swap').onclick=()=>{state.current=null;save();renderPlay()}}
function showProven(m,small){state.feeling=null;$('#notYetCard').classList.add('hidden');$('#activeCard').classList.add('hidden');$('#provenCard').classList.remove('hidden');$('#provenCard').innerHTML=`<div class="stamp">✓ PROVEN</div><h2>You have evidence.</h2><p class="hint">${small?'You made the resistance smaller and still moved.':'You did something you almost didn’t.'}</p><div class="tags" style="justify-content:center">${m.dimensions.map(x=>`<span class="pill">${x} ↑</span>`).join('')}</div><div class="reflection"><div class="eyebrow">HOW DID IT ACTUALLY FEEL?</div><div class="faces"><button>😣</button><button>😐</button><button>🙂</button><button>🔥</button></div></div><button class="primary" id="keep">KEEP MY PROOF</button>`;document.querySelectorAll('.faces button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.faces button').forEach(x=>x.classList.remove('chosen'));b.classList.add('chosen');state.feeling=b.textContent});$('#keep').onclick=()=>complete(m,small)}
function complete(m,small){if(state.completed.some(x=>x.id===(small?m.id+'-small':m.id)))return;const record={...m,id:small?m.id+'-small':m.id,originalId:m.id,completedAt:new Date().toISOString(),smaller:small,feeling:state.feeling};state.completed.push(record);m.dimensions.forEach(d=>state.dimensions[d]=(state.dimensions[d]||0)+1);m.identities.forEach((id,i)=>state.identities[id]=(state.identities[id]||0)+(small?1:2)+(i===0?1:0));state.current=small?m.id:null;state.active=false;state.small=false;state.feeling=null;save();renderAll();go('me')}
function identity(){if(state.completed.length<25)return null;let diversity=dims.filter(d=>state.dimensions[d]>=3).length;if(diversity<3)return null;return Object.entries(state.identities).sort((a,b)=>b[1]-a[1])[0][0]}
function renderJourney(){const max=Math.max(1,...Object.values(state.dimensions));$('#dimensionStats').innerHTML=dims.map(d=>`<div class="card stat"><div class="stat-row"><span>${d.toUpperCase()}</span><span>${state.dimensions[d]}</span></div><div class="track"><div class="fill" style="width:${state.dimensions[d]/max*100}%"></div></div></div>`).join('');const pos={Courage:[70,48],Connection:[180,112],'Self-Respect':[300,48],Creation:[160,200],Growth:[300,200]};$('#mapNodes').innerHTML=dims.map(d=>{let [x,y]=pos[d];let label=d==='Self-Respect'?['SELF-','RESPECT']:d==='Connection'?['CONNEC-','TION']:[d.toUpperCase()];return `<g class="node ${state.dimensions[d]===max&&max>1?'active':''}"><circle cx="${x}" cy="${y}" r="34"/>${label.map((t,i)=>`<text x="${x}" y="${y+(i-(label.length-1)/2)*11+3}">${t}</text>`).join('')}</g>`}).join('')}
function renderMe(){let count=state.completed.length;$('#meCount').textContent=count;let id=identity();$('#identityName').textContent=id?'THE '+id.toUpperCase():'EMERGING…';if(id){$('#identityCard').classList.remove('hidden');$('#identityCard').innerHTML=`<div class="eyebrow">A PATTERN IS EMERGING</div><h2>THE ${id.toUpperCase()}</h2><p>${identityCopy[id]}</p><p class="quote">You didn't choose this identity.<br>Your actions revealed it.</p>`}else{$('#identityCard').classList.toggle('hidden',count===0);if(count>0){let left=Math.max(0,25-count);$('#identityCard').innerHTML=`<div class="eyebrow">YOUR ACTIONS ARE SPEAKING</div><h2>KEEP PROVING IT.</h2><p>${left?`${left} more Proof${left===1?'':'s'} until the first identity reveal can unlock.`:'Build a little more diversity across your Journey.'}</p>`}}$('#passport').innerHTML=count?state.completed.slice().reverse().map((h,i)=>`<article class="card entry"><div class="top"><span>✓ PROOF #${String(count-i).padStart(3,'0')}</span><span>${h.dimensions.join(' · ')}</span></div><b>${h.title}</b><p>${h.smaller?'Smaller step completed: ':''}${h.smaller?h.notYet:h.mission}</p></article>`).join(''):`<div class="card empty">Complete your first mission. Your real-world evidence will live here.</div>`}
function renderAll(){$('#headerCount').textContent=state.completed.length;renderPlay();renderJourney();renderMe()}
function go(id){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('[data-nav]').forEach(x=>x.classList.toggle('selected',x.dataset.nav===id));window.scrollTo({top:0,behavior:'smooth'})}document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>go(b.dataset.nav));$('#resetBtn').onclick=()=>{if(confirm('Reset all PROOF prototype progress?')){localStorage.removeItem('proof-v1');location.reload()}};
Promise.resolve(window.PROOF_MISSIONS).then(data=>{missions=data;renderAll()}).catch(()=>{$('#missionCard').innerHTML='<p>Could not load the mission database. Run this folder through a local web server.</p>'});
